### Register a New User
POST http://localhost:3001/users/registration
Content-Type: application/json

{
  "email": "test00@example.com",
  "user_name": "test00",
  "password": "Test00"
}

### Log In to Get Token
POST http://localhost:3001/users/login
Content-Type: application/json

{
  "email": "test00@example.com",
  "user_name": "test00",
  "password": "Test00"
}

### Get User Information
GET http://localhost:3001/users/:user_id
Authorization: Bearer <token>

### Log Out User
POST http://localhost:3001/users/logout
Authorization: Bearer <token>

### Delete User by ID
DELETE http://localhost:3001/users/delete/:user_id
Authorization: Bearer <token>



POST http://localhost:3001/rating/ HTTP/1.1 
content-type: application/json

{ "rating":2, "movie_id":123, "user_id":1

}


### List all groups
GET http://localhost:3001/groups/all

### View a specific group by ID
GET http://localhost:3001/groups/all/2

### Delete a group by ID (only for the owner)
DELETE http://localhost:3001/groups/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJlbWFpbCI6InRlc3QwMEBnbWFpbC5jb20iLCJpYXQiOjE3MzM2NjQxNjUsImV4cCI6MTczMzcxODE2NX0.su7CbMwQSdFtQ7CUgGOdlcV2LSjs37Np_lqdW3ZPPSo

### Role a group by ID (only for the owner)
GET http://localhost:3001/groups/2/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJlbWFpbCI6InRlc3QwMEBleGFtcGxlLmNvbSIsImlhdCI6MTczMzc2MDAwMSwiZXhwIjoxNzMzODE0MDAxfQ.-8hIS2IcnIlAKzCRX93dyBjy-MRSK1jclY37wJMAGpw

###request join group
POST http://localhost:3001/groups/3/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJlbWFpbCI6InRlc3QwMEBleGFtcGxlLmNvbSIsImlhdCI6MTczMzc2MDAwMSwiZXhwIjoxNzMzODE0MDAxfQ.-8hIS2IcnIlAKzCRX93dyBjy-MRSK1jclY37wJMAGpw

